web:
  hosts:
    nginx:
      ansible_host: 192.168.56.150
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/nginx/virtualbox/private_key
  
    nginx2:
      ansible_host: 192.168.56.151
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/nginx2/virtualbox/private_key
